---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: team-2
  name: team-2

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: team-2
  name: team-2
  namespace: team-2

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: team-2
  name: team-2-reconciler
  namespace: team-2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: user-2
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:team-2:reconciler
- kind: ServiceAccount
  name: team-2
  namespace: team-2

