apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 1h0s
  url: https://kyverno.github.io/kyverno/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kyverno
      # version: 2.6.4
      sourceRef:
        kind: HelmRepository
        name: kyverno
  targetNamespace: kyverno
  serviceAccountName: helm-controller
  interval: 10m0s
  install:
    crds: CreateReplace
    createNamespace: true
  upgrade:
    crds: CreateReplace
  values:
    resourceFiltersExcludeNamespaces:
      - flux-system
